window.VOICES = {
 "Найди такой же": "naydi_takoy_zhe",
 "Найди такой же цвет": "naydi_takoy_zhe_tsvet",
 "Что лишнее?": "chto_lishnee",
 "Чья это тень?": "chya_eto_ten",
 "Найди ещё животное": "naydi_zhivotnoe",
 "Найди ещё фрукт": "naydi_frukt",
 "Найди ещё цветок": "naydi_tsvetok_more",
 "Самый большой": "samy_bolshoy",
 "Самый маленький": "samy_malenkiy",
 "Найди столько же": "naydi_stolko_zhe",
 "Слушай и найди": "slushay_i_naydi",
 "Молодец": "molodets",
 "Отлично": "otlichno",
 "Правильно": "pravilno",
 "Умница": "umnitsa",
 "Прекрасно": "prekrasno",
 "Почти": "pochti",
 "Попробуй ещё раз": "poprobuy",
 "Новый уровень": "novy_uroven",
 "Мост": "most",
 "Кошка": "koshka",
 "Собака": "sobaka",
 "Лошадь": "loshad",
 "Слон": "slon",
 "Лев": "lev",
 "Медведь": "medved",
 "Сова": "sova",
 "Утка": "utka",
 "Пингвин": "pingvin",
 "Рыба": "ryba",
 "Бабочка": "babochka",
 "Цветок": "tsvetok",
 "Дерево": "derevo",
 "Яблоко": "yabloko",
 "Гора": "gora",
 "Замок": "zamok",
 "Церковь": "tserkov"
};
